version: "3.3"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./gitignore/pg-data-storage:/var/lib/postgresql/data
        # copy the sql script to create tables
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
        # copy the sql script to populate tables
      - ./sql/populate-tables.sql:/docker-entrypoint-initdb.d/populate-tables.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
